import React from 'react';
import {useParams} from 'react-router-dom';
import makeStyles from '@mui/styles/makeStyles';
import {Box, Chip, Grid} from '@mui/material';

import {Header} from '../../shared/components/Texts';
import {Table, type TableColumn, type TableData} from '../../shared/components/Table';
import {useDeleteBusinessBookingMutation} from './BookingApi';
import {type BookingDto} from '../../autogenerated';
import FormatUtil from '../../shared/util/FormatUtil';
import {useGetBusinessAggregateByIdQuery} from '../business/BusinessApi';

const useStyles = makeStyles({
    box: {
        alignItems: 'center',
        display: 'flex',
        flexDirection: 'column',
    },
});

const mapBookingToTableData = (bookings: BookingDto[] | undefined | null): TableData =>
    bookings?.map((booking) => ({
        id: booking?.id ?? '',
        timeSlotId: booking?.timeSlotId ?? '',
        userEmail: booking?.userEmail ?? '',
        interval: FormatUtil.formatInterval(booking?.interval),
        date: booking?.date ?? '',
        capacity: booking?.capacity ?? '',
    })) ?? [];

export const BusinessBookingView: React.FC = () => {
    const {businessId} = useParams();
    const styles = useStyles();

    const {data: business} = useGetBusinessAggregateByIdQuery(businessId!);
    const [deleteBookingForBusiness] = useDeleteBusinessBookingMutation();

    const columns: TableColumn[] = [
        {title: 'id', field: 'id', hidden: true},
        {title: 'timeSlotId', field: 'timeSlotId', hidden: true},
        {title: 'User', field: 'userEmail'},
        {title: 'Interval', field: 'interval'},
        {title: 'Date', field: 'date'},
        {title: 'Capacity', field: 'capacity'},
    ];

    const actions = [
        {
            icon: () => <Chip size="small" label="Contact User" clickable color="primary" />,
            onClick: (_: React.ChangeEvent, rowData: BookingDto) => {
                console.log(rowData);
            },
        },
        {
            icon: () => <Chip size="small" label="Delete Booking" clickable color="secondary" />,
            onClick: async (_: React.ChangeEvent, rowData: BookingDto) => {
                await deleteBookingForBusiness({businessId: business!.id!, bookingId: rowData.id!});
            },
        },
    ];

    return (
        <Box className={styles.box}>
            <Header text="Bookings" />
            <Grid container justifyContent="center">
                <Grid item xs={8}>
                    <Table
                        actions={actions}
                        columns={columns}
                        title={business?.name ?? ''}
                        noDataMessage="No Bookings Yet"
                        data={mapBookingToTableData(business?.bookings)}
                    />
                </Grid>
            </Grid>
        </Box>
    );
};
