import React, {useState} from 'react';
import Chip from '@mui/material/Chip';
import makeStyles from '@mui/styles/makeStyles';

import {useDeleteUserBookingMutation} from './BookingApi';
import {Header} from '../../shared/components/Texts';
import {MapModal, defaultMapProps} from '../../shared/components/modal/MapModal';
import type {MapModalProps} from '../../shared/components/modal/MapModal';
import {Table, type TableData, type TableColumn} from '../../shared/components/Table';
import {useGetUserQuery} from '../user/UserApi';
import {type BookingDto} from '../../autogenerated';
import {formatInterval} from '../business/AllBusinessesView';
import {Box, Grid} from '@mui/material';

const useStyles = makeStyles({
    box: {
        alignItems: 'center',
        display: 'flex',
        flexDirection: 'column',
    },
});

const mapBookingsToTableData = (bookings: BookingDto[] | undefined | null): TableData =>
    bookings?.map((booking) => ({
        id: booking?.id ?? '',
        timeSlotId: booking?.timeSlotId ?? '',
        date: booking?.date ?? '',
        interval: formatInterval(booking?.interval),
        business: booking?.business ?? '',
        street: booking?.street ?? '',
    })) ?? [];

export const UserBookingView: React.FC = () => {
    const [mapModalInfo, setMapModalInfo] = useState<MapModalProps>(defaultMapProps);
    const styles = useStyles();

    const {data: getUserResponse} = useGetUserQuery();
    const [deleteBookingForUser] = useDeleteUserBookingMutation();

    const columns: TableColumn[] = [
        {title: 'id', field: 'id', hidden: true},
        {title: 'timeSlotId', field: 'timeSlotId', hidden: true},
        {title: 'Date', field: 'date'},
        {title: 'Interval', field: 'interval'},
        {title: 'Business & Zip', field: 'business'},
        {title: 'Street', field: 'street'},
    ];

    const actions = [
        {
            icon: () => <Chip size="small" label="Delete" clickable color="primary" />,
            tooltip: 'Delete Booking',
            onClick: async (_: any, rowData: Partial<BookingDto>) => {
                await deleteBookingForUser(rowData.id ?? '');
            },
        },
        {
            icon: () => <Chip size="small" label="See on map" clickable color="secondary" />,
            tooltip: 'Show location on map',
            onClick: (_: any, rowData: Partial<BookingDto>) => {
                setMapModalInfo({
                    open: true,
                    title: rowData.business ?? '',
                    zoom: 14,
                    center: [rowData.longitude as number, rowData.latitude as number],
                    markers: [[rowData.longitude as number, rowData.latitude as number], 13],
                });
            },
        },
    ];

    return (
        <Box className={styles.box}>
            <Header text="Your Bookings" />
            <Grid container justifyContent="center">
                <MapModal
                    open={mapModalInfo.open}
                    setVisible={() => setMapModalInfo(defaultMapProps)}
                    zoom={mapModalInfo.zoom}
                    center={mapModalInfo.center}
                    markers={mapModalInfo.markers}
                />
                <Grid item xs={7}>
                    <Table
                        actions={actions}
                        columns={columns}
                        data={mapBookingsToTableData(getUserResponse?.user?.bookings)}
                        title="Bookings"
                        emptyMessage="No Bookings Yet"
                    />
                </Grid>
            </Grid>
        </Box>
    );
};
