import {baseApi, USER_TAG} from '../../app/Store';
import {UserApi} from '../../autogenerated';
import type {UpdateUserRequest, UserDto} from '../../autogenerated';
import {apiMutation, apiQuery} from '../../shared/api/Api';

const USER_UPDATED_MSG = 'Info Updated.';

const userApi = baseApi.injectEndpoints({
    endpoints: (builder) => ({
        getUser: builder.query<UserDto | undefined, void>({
            providesTags: [USER_TAG],
            queryFn: async (_, api) => ({
                data: await apiQuery(async (queryApi) => (await queryApi.getUser()).data.user, api),
            }),
        }),
        usersNotEmployedByBusiness: builder.query<UserDto[], string>({
            queryFn: async (businessId, api) => ({
                data: await apiQuery(
                    async (queryApi) =>
                        (
                            await queryApi.getUsersNotAlreadyEmployedByBusiness(businessId)
                        ).data.users ?? [],
                    api
                ),
            }),
        }),
        updateUser: builder.mutation<void, UpdateUserRequest>({
            invalidatesTags: [USER_TAG],
            queryFn: async (updateUserRequest, api) => ({
                data: await apiMutation(
                    async (userApi) => userApi.updateUser(updateUserRequest),
                    UserApi,
                    api,
                    {message: USER_UPDATED_MSG}
                ),
            }),
        }),
    }),
});

export const {useGetUserQuery, useUsersNotEmployedByBusinessQuery, useUpdateUserMutation} = userApi;
