import Cookies from 'js-cookie';

import {
    BUSINESS_ALL_TAG,
    BUSINESS_BY_OWNER_TAG,
    BUSINESS_TAG,
    baseApi,
    USER_TAG,
} from '../../app/Store';
import {
    BusinessApi,
    Configuration,
    QueryApi,
    type CreateBusinessRequest,
    type GetAllBusinessesResponse,
    type UpdateBusinessRequest,
    type GetBusinessResponse,
} from '../../autogenerated';

const queryApi = new QueryApi(new Configuration({accessToken: Cookies.get('access_token')}));
const businessApiInstance = new BusinessApi(
    new Configuration({accessToken: Cookies.get('access_token')})
);

const businessApi = baseApi.injectEndpoints({
    endpoints: (builder) => ({
        getBusinessById: builder.query<GetBusinessResponse, string>({
            providesTags: [BUSINESS_TAG],
            queryFn: async (businessId) => {
                try {
                    const response = await queryApi.getBusiness(businessId);
                    return {data: response.data};
                } catch (error) {
                    return {error} as any;
                }
            },
        }),
        getAllBusinesses: builder.query<GetAllBusinessesResponse, void>({
            providesTags: [BUSINESS_TAG, BUSINESS_BY_OWNER_TAG],
            queryFn: async () => {
                try {
                    const response = await queryApi.getAllBusinesses();
                    return {data: response.data};
                } catch (error) {
                    return {error} as any;
                }
            },
        }),
        createBusiness: builder.mutation<void, CreateBusinessRequest>({
            invalidatesTags: [BUSINESS_ALL_TAG, BUSINESS_BY_OWNER_TAG, USER_TAG],
            queryFn: async (createBusinessRequest) => {
                try {
                    await businessApiInstance.createBusiness(createBusinessRequest);
                } catch (error) {
                    return {error} as any;
                }
            },
        }),
        updateBusiness: builder.mutation<void, UpdateBusinessRequest>({
            invalidatesTags: [BUSINESS_ALL_TAG, BUSINESS_BY_OWNER_TAG],
            queryFn: async (updateBusinessRequest) => {
                try {
                    await businessApiInstance.updateBusiness(updateBusinessRequest);
                } catch (error) {
                    return {error} as any;
                }
            },
        }),
    }),
});

export const {
    useGetBusinessByIdQuery,
    useGetAllBusinessesQuery,
    useUpdateBusinessMutation,
    useCreateBusinessMutation,
} = businessApi;
