import React from 'react';
import {useParams} from 'react-router-dom';
import {Col, Row} from 'react-bootstrap';
import makeStyles from '@mui/styles/makeStyles';

import {businessValidationSchema} from './BusinessValidation';
import {FormCard} from '../../shared/components/card/FormCard';
import {Header} from '../../shared/components/Texts';
import {useAddress} from '../../shared/hooks/useAddress';
import {type Index, useForm} from '../../shared/hooks/useForm';
import {useGetBusinessAggregateByIdQuery, useUpdateBusinessMutation} from './BusinessApi';
import {BusinessType, type UpdateBusinessRequest} from '../../autogenerated';

const useStyles = makeStyles(() => ({
    col: {
        marginTop: 25,
    },
    row: {
        justifyContent: 'center',
    },
}));

const getIndex = (key: string) => {
    if (key === 'name') return 1;
    if (key === 'zip') return 2;
    if (key === 'street') return 3;
    if (key === 'type') return 4;
    if (key === 'capacity') return 5;
    if (key === 'timeSlotLengthInMinutes') return 6;
    if (key === 'opens') return 7;
    if (key === 'closes') return 8;
};

export const BusinessProfileView: React.FC = () => {
    const {businessId} = useParams();
    const styles = useStyles();

    const {data: business} = useGetBusinessAggregateByIdQuery(businessId!);
    const [updateBusiness] = useUpdateBusinessMutation();

    const formValues = {
        name: business?.name ?? '',
        zip: business?.address?.zip,
        street: business?.address?.street,
        type: business?.type,
        capacity: business?.capacity,
        timeSlotLengthInMinutes: business?.timeSlotLengthInMinutes,
        opens: business?.businessHours?.start?.hour?.toString() ?? '',
        closes: business?.businessHours?.end?.hour?.toString() ?? '',
    };

    const {formHandler} = useForm<typeof formValues & Index>({
        initialValues: formValues,
        validationSchema: businessValidationSchema,
        onSubmit: async (formValues) => {
            const address = addressHandler.addresses.find(
                (address) => address.street === formValues.street
            );

            await updateBusiness({
                ...formValues,
                businessId: business?.id,
                address,
                businessHours: {
                    start: {hour: parseInt(formValues.opens)},
                    end: {hour: parseInt(formValues.closes)},
                },
            } as UpdateBusinessRequest);
        },
    });

    const addressHandler = useAddress(formHandler);

    return (
        <>
            <Row className={styles.row}>
                <Header text={`Manage ${business?.name}`} />
            </Row>
            <Row className={styles.row}>
                <Col sm={12} md={6} lg={10} className={styles.col}>
                    <FormCard
                        title="Business Data"
                        formData={formValues}
                        entity={business}
                        buttonText="Save Changes"
                        primaryDisabled={!formHandler.isValid}
                        buttonAction={formHandler.handleSubmit}
                        formHandler={formHandler}
                        addressHandler={addressHandler}
                        getIndex={getIndex}
                        selectOptions={Object.values(BusinessType)}
                    />
                </Col>
            </Row>
        </>
    );
};
