import {createSlice} from '@reduxjs/toolkit';

import type {BusinessDto} from '../../autogenerated';
import type {RootState} from '../../app/Store';

interface BusinessState {
    current: BusinessDto | undefined;
}

const initialBusinessState: BusinessState = {
    current: undefined,
};

export const businessSlice = createSlice({
    name: 'business',
    initialState: initialBusinessState,
    reducers: {
        setCurrentBusiness: (state, {payload}) => {
            state.current = payload;
        },
    },
});

export const selectCurrentBusiness = (state: RootState) => state.business.current;

export const {setCurrentBusiness} = businessSlice.actions;

export default businessSlice.reducer;
