version: "3.4"

networks:
  clup-network:
    driver: bridge

services:
  db:
    container_name: clup-postgres
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    networks:
      - clup-network

  server:
    container_name: clup-server
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Settings__ConnectionStrings__Development=User ID=postgres;Password=postgres;Server=clup-postgres;Port=5432;Database=postgres;Pooling=true
      - Settings__Url=http://+:5001
    build:
      context: .
      dockerfile: src/CLup.API/Dockerfile
    ports:
      - "5001:5001"
    restart: always
    depends_on:
      - postgres
    networks:
      - clup-network

  client:
    container_name: clup-client
    build:
      context: .
      dockerfile: ./src/CLup.WebUI/Dockerfile
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - server
    networks:
      - clup-network

  seq:
    container_name: clup-seq
    image: datalust/seq:latest
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:5341"
      - "8081:80"
    restart: always
    networks:
      - clup-network