version: "3.4"

services:
  db:
    container_name: clup_db
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - "ACCEPT_EULA=Y"
      - "SA_PASSWORD=Secret_paSS123"
    ports:
      - "1433:1433"

  server:
    container_name: clup_server
    build:
      context: server
      dockerfile: Dockerfile
    volumes:
      - ./server:/app
    command: ["dotnet", "watch", "run"]
    ports:
      - "5001:5001"
    restart: always
    depends_on:
      - db

  client:
    container_name: clup_client
    build:
      context: client
      dockerfile: Dockerfile
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - server
    links:
      - server
# docker-compose build --no-cache server client

