version: "3.4"

services:
  db:
    container_name: clup-db
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'

  server:
    container_name: clup-server
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    build:
      context: ./src
      dockerfile: CLup.API/Dockerfile
    ports:
      - "5001:5001"
    restart: always
    depends_on:
      - db

  client:
    container_name: clup-client
    build:
      context: ./src/CLup.WebUI
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - server
    links:
      - server

  seq:
    container_name: clup-seq
    image: datalust/seq:latest
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:5341"
      - "8081:80"
    restart: always
