version: "3.4"

services:
  db:
    container_name: clup_db
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - "ACCEPT_EULA=Y"
      - "SA_PASSWORD=Secret_paSS123"
    ports:
      - "1433:1433"

  server:
    container_name: clup_server
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    build:
      context: ./src
      dockerfile: CLup.API/Dockerfile
    ports:
      - "5001:5001"
    restart: always
    depends_on:
      - db

  client:
    container_name: clup_client
    build:
      context: ./src/CLup.WebUI
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - server
    links:
      - server
