version: "3.4"

services:
  db:
    container_name: clup_db
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'

  server:
    container_name: clup_server
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    build:
      context: ./src
      dockerfile: CLup.API/Dockerfile
    ports:
      - "5001:5001"
    restart: always
    depends_on:
      - db

  client:
    container_name: clup_client
    build:
      context: ./src/CLup.WebUI
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - server
    links:
      - server
