import type {AxiosResponse} from 'axios';
import Cookies from 'js-cookie';
import {type SerializedError} from '@reduxjs/toolkit';
import {type BaseQueryApi} from '@reduxjs/toolkit/query';

import {Configuration, QueryApi, type TokenResponse} from '../../autogenerated';
import {type ApiState, setApiState} from './ApiState';

export function getConfiguration() {
    return new Configuration({
        basePath: process.env.REACT_APP_API_URL,
        accessToken: Cookies.get('access_token'),
    });
}

export async function apiQuery<T>(
    query: (queryApi: QueryApi) => Promise<AxiosResponse<T, any>>,
    api: BaseQueryApi,
    successInfo?: Omit<ApiState, 'error'>
): Promise<T> {
    try {
        const response = await query(new QueryApi(getConfiguration()));
        if (successInfo) {
            api.dispatch(setApiState(successInfo));
        }

        return response.data;
    } catch (error) {
        const err = error as SerializedError;
        api.dispatch(setApiState({message: err.message, error: true}));
        return {error} as any;
    }
}

export async function apiMutation(
    mutation: () => Promise<AxiosResponse<void | TokenResponse, any>>,
    api: BaseQueryApi,
    successInfo?: Omit<ApiState, 'error'>
): Promise<void> {
    try {
        await mutation();
        if (successInfo) {
            api.dispatch(setApiState(successInfo));
        }
    } catch (error) {
        const err = error as SerializedError;
        api.dispatch(setApiState({message: err.message, error: true}));
    }
}
