import type {Address} from '../../autogenerated';
import ApiCaller from '../api/ApiCaller';

// TODO: Move to RTK Query?

const DAWA_ZIP_URL = 'https://dawa.aws.dk/postnumre?landpostnumre&struktur=mini';

const getAddressUrl = (zip: number) =>
    `https://dawa.aws.dk/adgangsadresser?struktur=mini&postnr=${zip.toString()}`;

type DawaZip = {
    nr: string;
    navn: string;
};

type DawaAddress = {
    vejnavn: string;
    husnr: string;
    x: number;
    y: number;
};

export type ExtendedAddress = Address & {
    zipCity: string;
};

export async function fetchZips(): Promise<ExtendedAddress[]> {
    const dawaZips = await ApiCaller.get<DawaZip[]>(DAWA_ZIP_URL);

    const zips = dawaZips.map(
        (dawaZip) =>
            ({
                street: '',
                city: dawaZip.navn,
                zip: parseInt(dawaZip.nr),
                coords: {},
                zipCity: `${dawaZip.nr} - ${dawaZip.navn}`,
            } as ExtendedAddress)
    );

    return zips;
}

export async function fetchAddresses(
    address: ExtendedAddress | undefined
): Promise<ExtendedAddress[]> {
    if (address) {
        const dawaAddresses = await ApiCaller.get<DawaAddress[]>(getAddressUrl(address.zip));

        const addresses: ExtendedAddress[] = dawaAddresses.map((dawaAddress) => ({
            ...address,
            street: `${dawaAddress.vejnavn} ${dawaAddress.husnr}`,
            coords: {longitude: dawaAddress.y, latitude: dawaAddress.x},
        }));

        return addresses;
    }

    return [];
}

export default {
    fetchAddresses,
    fetchZips,
};
