import React from 'react';
import Chip from '@mui/material/Chip';
import {Col, Row} from 'react-bootstrap';
import makeStyles from '@mui/styles/makeStyles';

import {ErrorView} from '../../shared/views/ErrorView';
import {Header} from '../../shared/components/Texts';
import {selectCurrentBusiness} from '../business/BusinessState';
import {useAppSelector} from '../../app/Store';
import type {TableColumn} from '../../shared/components/Table';
import {TableContainer} from '../../shared/containers/TableContainer';
import {useDeleteEmployeeMutation} from './EmployeeApi';
import {type EmployeeDto} from '../../autogenerated';

const useStyles = makeStyles(() => ({
    row: {
        justifyContent: 'center',
    },
}));

export const EmployeeView: React.FC = () => {
    const styles = useStyles();

    const business = useAppSelector(selectCurrentBusiness);
    const [deleteEmployee] = useDeleteEmployeeMutation();

    if (!business) {
        return <ErrorView />;
    }

    const columns: TableColumn[] = [
        {title: 'BusinessId', field: 'businessId', hidden: true},
        {title: 'Name', field: 'name'},
        {title: 'Employed Since', field: 'employedSince'},
        {title: 'Private Email', field: 'privateEmail'},
        {title: 'Company Email', field: 'companyEmail'},
    ];

    const actions = [
        {
            icon: () => <Chip size="small" label="Remove Employee" clickable color="primary" />,
            onClick: async (_: any, employee: EmployeeDto) => {
                await deleteEmployee(employee.id ?? '');
            },
        },
    ];

    return (
        <>
            <Row className={styles.row}>
                <Header text={business.name ?? ''} />
            </Row>
            <Row className={styles.row}>
                <Col sm={6} md={8} lg={6} xl={10}>
                    <TableContainer
                        actions={actions}
                        columns={columns}
                        tableTitle="Employees"
                        tableData={business.employees ?? []}
                        emptyMessage="No Employees Yet"
                    />
                </Col>
            </Row>
        </>
    );
};
