import React from 'react';
import {useParams} from 'react-router-dom';
import Chip from '@mui/material/Chip';
import {Col, Row} from 'react-bootstrap';
import makeStyles from '@mui/styles/makeStyles';

import {Header} from '../../shared/components/Texts';
import {Table, type TableData, type TableColumn} from '../../shared/components/Table';
import {useDeleteEmployeeMutation} from './EmployeeApi';
import {type EmployeeDto} from '../../autogenerated';
import {useGetBusinessAggregateByIdQuery} from '../business/BusinessApi';

const useStyles = makeStyles(() => ({
    row: {
        justifyContent: 'center',
    },
}));

export const EmployeeView: React.FC = () => {
    const {businessId} = useParams();
    const styles = useStyles();

    const {data: business} = useGetBusinessAggregateByIdQuery(businessId!);
    const [deleteEmployee] = useDeleteEmployeeMutation();

    const columns: TableColumn[] = [
        {title: 'BusinessId', field: 'businessId', hidden: true},
        {title: 'Name', field: 'name'},
        {title: 'Employed Since', field: 'employedSince'},
        {title: 'Private Email', field: 'privateEmail'},
        {title: 'Company Email', field: 'companyEmail'},
    ];

    const actions = [
        {
            icon: () => <Chip size="small" label="Remove Employee" clickable color="primary" />,
            onClick: async (_: any, employee: EmployeeDto) => {
                await deleteEmployee(employee.id ?? '');
            },
        },
    ];

    return (
        <>
            <Row className={styles.row}>
                <Header text={business?.name ?? ''} />
            </Row>
            <Row className={styles.row}>
                <Col sm={6} md={8} lg={6} xl={10}>
                    <Table
                        actions={actions}
                        columns={columns}
                        title="Employees"
                        data={business?.employees as TableData}
                        noDataMessage="No Employees Yet"
                    />
                </Col>
            </Row>
        </>
    );
};
