import {BUSINESS_BY_OWNER_TAG, baseApi, USER_TAG, BUSINESS_AGGREGATE_TAG} from '../../app/Store';
import {
    MessageApi,
    type SendUserMessageRequest,
    type SendBusinessMessageRequest,
    type MarkMessageAsDeletedForUserRequest,
    type MarkMessageAsDeletedForBusinessRequest,
} from '../../autogenerated';
import {apiMutation} from '../../shared/api/Api';

const MESSAGE_SENT = 'Message successfully send';

const messageApi = baseApi.injectEndpoints({
    endpoints: (builder) => ({
        sendUserMessage: builder.mutation<void, SendUserMessageRequest>({
            invalidatesTags: [BUSINESS_AGGREGATE_TAG, BUSINESS_BY_OWNER_TAG, USER_TAG],
            queryFn: async (sendUserMessageRequest, api) => ({
                data: await apiMutation(
                    async (messageApi) => await messageApi.sendUserMessage(sendUserMessageRequest),
                    MessageApi,
                    api,
                    {message: MESSAGE_SENT}
                ),
            }),
        }),
        sendBusinessMessage: builder.mutation<void, SendBusinessMessageRequest>({
            invalidatesTags: [BUSINESS_AGGREGATE_TAG, BUSINESS_BY_OWNER_TAG, USER_TAG],
            queryFn: async (sendBusinessMessageRequest, api) => ({
                data: await apiMutation(
                    async (messageApi) =>
                        await messageApi.sendBusinessMessage(sendBusinessMessageRequest),
                    MessageApi,
                    api
                ),
            }),
        }),
        markMessageAsDeletedForUser: builder.mutation<void, MarkMessageAsDeletedForUserRequest>({
            invalidatesTags: [USER_TAG],
            queryFn: async (markMessageAsDeletedForUserRequest, api) => ({
                data: await apiMutation(
                    async (messageApi) =>
                        await messageApi.markMessageAsDeletedForUser(
                            markMessageAsDeletedForUserRequest
                        ),
                    MessageApi,
                    api
                ),
            }),
        }),
        markMessageAsDeletedForBusiness: builder.mutation<
            void,
            MarkMessageAsDeletedForBusinessRequest
        >({
            invalidatesTags: [BUSINESS_AGGREGATE_TAG, BUSINESS_BY_OWNER_TAG],
            queryFn: async (markMessageAsDeletedForBusinessRequest, api) => ({
                data: await apiMutation(
                    async (messageApi) =>
                        await messageApi.markMessageAsDeletedForBusiness(
                            markMessageAsDeletedForBusinessRequest
                        ),
                    MessageApi,
                    api
                ),
            }),
        }),
    }),
});

export const {
    useSendUserMessageMutation,
    useSendBusinessMessageMutation,
    useMarkMessageAsDeletedForUserMutation,
    useMarkMessageAsDeletedForBusinessMutation,
} = messageApi;
