import React from 'react';
import Chip from '@mui/material/Chip';
import {Col, Row} from 'react-bootstrap';
import makeStyles from '@mui/styles/makeStyles';

import {useDeleteTimeSlotMutation} from './TimeSlotApi';
import {ErrorView} from '../../shared/views/ErrorView';
import {Header} from '../../shared/components/Texts';
import {selectCurrentBusiness} from '../business/BusinessState';
import {Table, type TableData, type TableColumn} from '../../shared/components/Table';
import {useAppSelector} from '../../app/Store';
import {type TimeSlotDto} from '../../autogenerated';
import {formatInterval} from '../business/AllBusinessesView';

const useStyles = makeStyles(() => ({
    row: {
        justifyContent: 'center',
    },
}));

export const mapTimeSlotsToTableData = (timeSlots: TimeSlotDto[] | undefined | null): TableData =>
    timeSlots?.map((timeSlot) => ({
        timeSlotId: timeSlot.id ?? '',
        date: timeSlot.date ?? '',
        interval: formatInterval(timeSlot.timeInterval),
        capacity: timeSlot.capacity ?? '',
    })) ?? [];

export const TimeSlotView: React.FC = () => {
    const styles = useStyles();
    const business = useAppSelector(selectCurrentBusiness);
    const [deleteTimeSlot] = useDeleteTimeSlotMutation();

    if (!business) {
        return <ErrorView />;
    }

    const columns: TableColumn[] = [
        {title: 'timeSlotId', field: 'timeSlotId', hidden: true},
        {title: 'Date', field: 'date'},
        {title: 'Interval', field: 'interval'},
        {title: 'Capacity', field: 'capacity'},
    ];

    const actions = [
        {
            icon: () => <Chip size="small" label="Delete Time Slot" clickable color="primary" />,
            onClick: async (_: any, timeSlot: TimeSlotDto) => {
                await deleteTimeSlot({
                    businessId: business.id ?? '',
                    timeSlotId: timeSlot.id ?? '',
                });
            },
        },
    ];

    return (
        <>
            <Row className={styles.row}>
                <Header text={business.name ?? ''} />
            </Row>
            <Row className={styles.row}>
                <Col sm={6} md={8} lg={6} xl={10}>
                    <Table
                        actions={actions}
                        columns={columns}
                        data={mapTimeSlotsToTableData(business.timeSlots)}
                        title="Time Slots"
                        emptyMessage="No Time Slots Yet"
                    />
                </Col>
            </Row>
        </>
    );
};
