import Cookies from 'js-cookie';

import {BUSINESS_BY_OWNER_TAG, BUSINESS_TAG, baseApi, USER_TAG} from '../../app/Store';
import {Configuration, TimeSlotApi, type GenerateTimeSlotsRequest} from '../../autogenerated';
import {MANAGE_TIMESLOTS_ROUTE} from '../../app/Routes';
import {apiMutation} from '../../shared/api/Api';

const TIMESLOT_DELETED_MSG = 'Time slot Deleted';

const TIMESLOTS_GENERATED_SUCCESS_INFO = {
    message: 'Success! Press see time slots to manage time slots.',
    toastInfo: {buttonText: 'See time slots', navigateTo: MANAGE_TIMESLOTS_ROUTE},
};

const timeSlotApiInstance = new TimeSlotApi(
    new Configuration({accessToken: Cookies.get('access_token')})
);

const timeSlotApi = baseApi.injectEndpoints({
    endpoints: (builder) => ({
        generateTimeSlots: builder.mutation<void, GenerateTimeSlotsRequest>({
            invalidatesTags: [BUSINESS_TAG, BUSINESS_BY_OWNER_TAG],
            queryFn: async (generateTimeSlotsRequest, api) => ({
                data: await apiMutation(
                    async () =>
                        await timeSlotApiInstance.generateTimeSlots(generateTimeSlotsRequest),
                    api,
                    TIMESLOTS_GENERATED_SUCCESS_INFO
                ),
            }),
        }),
        deleteTimeSlot: builder.mutation<void, {timeSlotId: string; businessId: string}>({
            invalidatesTags: [BUSINESS_TAG, BUSINESS_BY_OWNER_TAG, USER_TAG],
            queryFn: async (request, api) => ({
                data: await apiMutation(
                    async () =>
                        await timeSlotApiInstance.deleteTimeSlot(
                            request.timeSlotId,
                            request.businessId
                        ),
                    api,
                    {message: TIMESLOT_DELETED_MSG}
                ),
            }),
        }),
    }),
});

export const {useGenerateTimeSlotsMutation, useDeleteTimeSlotMutation} = timeSlotApi;
