#!/bin/bash

SPEC_URL="http://localhost:5001/swagger/v1/swagger.json"
OUTPUT_DIR="../src/CLup.WebUI/src/autogenerated"

# Ensure the OpenAPI Generator CLI is installed
if ! npm list -g @openapitools/openapi-generator-cli > /dev/null; then
  echo "@openapitools/openapi-generator-cli is not installed. Installing..."
  npm install -g @openapitools/openapi-generator-cli

  if [ $? -eq 0 ]; then
    echo "@openapitools/openapi-generator-cli installed successfully."
  else
    echo "Failed to install @openapitools/openapi-generator-cli."
    exit 1
  fi
fi

# Fetch the OpenAPI specification
curl $SPEC_URL -o api-spec.json

if [ $? -eq 0 ]; then
    echo "OpenAPI specification retrieved successfully."

    # Clear the output directory before generating new client
    rm -rf $OUTPUT_DIR/*
    mkdir -p $OUTPUT_DIR

    openapi-generator-cli generate -i api-spec.json -g typescript-axios -o $OUTPUT_DIR
    rm api-spec.json
    if [ $? -eq 0 ]; then
        echo "TypeScript client generated successfully in $OUTPUT_DIR"
    else
        echo "Failed to generate TypeScript client."
    fi
else
    echo "Failed to retrieve the OpenAPI specification from $SPEC_URL"
fi

rm openapitools.json
