// <auto-generated />
using System;
using Logic.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CLup.Migrations
{
    [DbContext(typeof(CLupContext))]
    [Migration("20201211115504_BookingWithBusinessId")]
    partial class BookingWithBusinessId
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Logic.Bookings.Booking", b =>
                {
                    b.Property<string>("UserEmail")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TimeSlotId")
                        .HasColumnType("int");

                    b.Property<int>("BusinessId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UserEmail", "TimeSlotId");

                    b.HasIndex("TimeSlotId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            UserEmail = "h@h.com",
                            TimeSlotId = 1,
                            BusinessId = 1
                        },
                        new
                        {
                            UserEmail = "h@h.com",
                            TimeSlotId = 2,
                            BusinessId = 1
                        },
                        new
                        {
                            UserEmail = "h@h.com",
                            TimeSlotId = 3,
                            BusinessId = 1
                        });
                });

            modelBuilder.Entity("Logic.BusinessOwners.BusinessOwner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("UserEmail")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserEmail")
                        .IsUnique()
                        .HasFilter("[UserEmail] IS NOT NULL");

                    b.ToTable("BusinessOwners");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            UserEmail = "h@h.com"
                        });
                });

            modelBuilder.Entity("Logic.Businesses.Business", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BusinessOwnerId")
                        .HasColumnType("int");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<double>("Closes")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<double>("Opens")
                        .HasColumnType("float");

                    b.Property<string>("OwnerEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TimeSlotLength")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Zip")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BusinessOwnerId");

                    b.ToTable("Businesses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 50,
                            Closes = 16.0,
                            Name = "Cool",
                            Opens = 10.0,
                            OwnerEmail = "h@h.com",
                            TimeSlotLength = 50,
                            Type = "Supermarket",
                            Zip = 3520
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 40,
                            Closes = 14.0,
                            Name = "Shop",
                            Opens = 9.0,
                            OwnerEmail = "h@h.com",
                            TimeSlotLength = 20,
                            Type = "Museum",
                            Zip = 3520
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 30,
                            Closes = 15.300000000000001,
                            Name = "1337",
                            Opens = 8.3000000000000007,
                            OwnerEmail = "h@h.com",
                            TimeSlotLength = 10,
                            Type = "Kiosk",
                            Zip = 4720
                        });
                });

            modelBuilder.Entity("Logic.TimeSlots.TimeSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BusinessId")
                        .HasColumnType("int");

                    b.Property<string>("BusinessName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("End")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.ToTable("TimeSlots");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BusinessId = 1,
                            BusinessName = "Cool",
                            Capacity = 50,
                            End = new DateTime(2020, 12, 11, 16, 55, 3, 743, DateTimeKind.Local).AddTicks(7467),
                            Start = new DateTime(2020, 12, 11, 15, 55, 3, 741, DateTimeKind.Local).AddTicks(2828)
                        },
                        new
                        {
                            Id = 2,
                            BusinessId = 1,
                            BusinessName = "Cool",
                            Capacity = 40,
                            End = new DateTime(2020, 12, 11, 17, 55, 3, 743, DateTimeKind.Local).AddTicks(7795),
                            Start = new DateTime(2020, 12, 11, 16, 55, 3, 743, DateTimeKind.Local).AddTicks(7789)
                        },
                        new
                        {
                            Id = 3,
                            BusinessId = 1,
                            BusinessName = "Cool",
                            Capacity = 30,
                            End = new DateTime(2020, 12, 11, 18, 55, 3, 743, DateTimeKind.Local).AddTicks(7798),
                            Start = new DateTime(2020, 12, 11, 17, 55, 3, 743, DateTimeKind.Local).AddTicks(7797)
                        });
                });

            modelBuilder.Entity("Logic.Users.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Zip")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "h@h.com",
                            Name = "Jens",
                            Password = "$2a$11$c.y.o2s.KGYj5uv9cldeZu2FZ1axUY97f47Gkq5HALb1W4mu/O05O",
                            Zip = "3520"
                        });
                });

            modelBuilder.Entity("Logic.Bookings.Booking", b =>
                {
                    b.HasOne("Logic.TimeSlots.TimeSlot", "TimeSlot")
                        .WithMany("Bookings")
                        .HasForeignKey("TimeSlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Logic.Users.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Logic.Businesses.Business", b =>
                {
                    b.HasOne("Logic.BusinessOwners.BusinessOwner", null)
                        .WithMany("Businesses")
                        .HasForeignKey("BusinessOwnerId");
                });

            modelBuilder.Entity("Logic.TimeSlots.TimeSlot", b =>
                {
                    b.HasOne("Logic.Businesses.Business", null)
                        .WithMany("TimeSlots")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
