// <auto-generated />
using System;
using Logic.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CLup.Migrations
{
    [DbContext(typeof(CLupContext))]
    [Migration("20201220231658_Second")]
    partial class Second
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Logic.Bookings.Booking", b =>
                {
                    b.Property<string>("UserEmail")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TimeSlotId")
                        .HasColumnType("int");

                    b.Property<int>("BusinessId")
                        .HasColumnType("int");

                    b.HasKey("UserEmail", "TimeSlotId");

                    b.HasIndex("TimeSlotId");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            UserEmail = "h@h.com",
                            TimeSlotId = 1,
                            BusinessId = 1
                        },
                        new
                        {
                            UserEmail = "h@h.com",
                            TimeSlotId = 2,
                            BusinessId = 1
                        },
                        new
                        {
                            UserEmail = "h@h.com",
                            TimeSlotId = 3,
                            BusinessId = 1
                        });
                });

            modelBuilder.Entity("Logic.BusinessOwners.BusinessOwner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("UserEmail")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserEmail")
                        .IsUnique()
                        .HasFilter("[UserEmail] IS NOT NULL");

                    b.ToTable("BusinessOwners");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            UserEmail = "h@h.com"
                        });
                });

            modelBuilder.Entity("Logic.Businesses.Business", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BusinessOwnerId")
                        .HasColumnType("int");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Closes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Opens")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TimeSlotLength")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Zip")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BusinessOwnerId");

                    b.ToTable("Businesses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 50,
                            Closes = "16.00",
                            Name = "Cool",
                            Opens = "10.00",
                            OwnerEmail = "h@h.com",
                            TimeSlotLength = 50,
                            Type = "Supermarket",
                            Zip = 3520
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 40,
                            Closes = "14.00",
                            Name = "Shop",
                            Opens = "09.00",
                            OwnerEmail = "h@h.com",
                            TimeSlotLength = 20,
                            Type = "Museum",
                            Zip = 3520
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 30,
                            Closes = "15.30",
                            Name = "1337",
                            Opens = "08.30",
                            OwnerEmail = "h@h.com",
                            TimeSlotLength = 10,
                            Type = "Kiosk",
                            Zip = 4720
                        });
                });

            modelBuilder.Entity("Logic.TimeSlots.TimeSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BusinessId")
                        .HasColumnType("int");

                    b.Property<string>("BusinessName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("End")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.ToTable("TimeSlots");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BusinessId = 1,
                            BusinessName = "Cool",
                            Capacity = 50,
                            End = new DateTime(2020, 12, 21, 4, 16, 57, 582, DateTimeKind.Local).AddTicks(2778),
                            Start = new DateTime(2020, 12, 21, 3, 16, 57, 579, DateTimeKind.Local).AddTicks(5364)
                        },
                        new
                        {
                            Id = 2,
                            BusinessId = 1,
                            BusinessName = "Cool",
                            Capacity = 40,
                            End = new DateTime(2020, 12, 21, 5, 16, 57, 582, DateTimeKind.Local).AddTicks(3128),
                            Start = new DateTime(2020, 12, 21, 4, 16, 57, 582, DateTimeKind.Local).AddTicks(3122)
                        },
                        new
                        {
                            Id = 3,
                            BusinessId = 1,
                            BusinessName = "Cool",
                            Capacity = 30,
                            End = new DateTime(2020, 12, 21, 6, 16, 57, 582, DateTimeKind.Local).AddTicks(3178),
                            Start = new DateTime(2020, 12, 21, 5, 16, 57, 582, DateTimeKind.Local).AddTicks(3177)
                        });
                });

            modelBuilder.Entity("Logic.Users.User", b =>
                {
                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Zip")
                        .HasColumnType("int");

                    b.HasKey("Email");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Email = "h@h.com",
                            Id = 1,
                            Name = "Jens",
                            Password = "$2a$11$8RsSUEKNfLG9jZSEyWniueh3AtZ1VtIMHVt3jZOBqLGt9wi.XPm4e",
                            Zip = 3520
                        });
                });

            modelBuilder.Entity("Logic.Bookings.Booking", b =>
                {
                    b.HasOne("Logic.TimeSlots.TimeSlot", "TimeSlot")
                        .WithMany("Bookings")
                        .HasForeignKey("TimeSlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Logic.Users.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserEmail")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Logic.Businesses.Business", b =>
                {
                    b.HasOne("Logic.BusinessOwners.BusinessOwner", null)
                        .WithMany("Businesses")
                        .HasForeignKey("BusinessOwnerId");
                });

            modelBuilder.Entity("Logic.TimeSlots.TimeSlot", b =>
                {
                    b.HasOne("Logic.Businesses.Business", "Business")
                        .WithMany("TimeSlots")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
